### ISSUE TITLE
Use ConfigSchema to validate the config map used for initialization

### ISSUE THREAD

**Issue by jliersch** [envire/envire-envire_types#5]
# Situation
Currently the types check if all required keys are present in the given configmap using a conjunction. If it fails, a generic error message regarding missing keys is printed.

# Task
For each type, define a config schema to be used by configmaps/ConfigSchema to validate the given config on construction of the type objects.

**Comment by jliersch** [comment]
Related branch: https://github.com/envire/envire-envire_types/tree/add_config_schemas

**Comment by jliersch** [comment]
validating minValue of motor types currently claims invalid data types:

```
ConfigSchema::validate_types: Invalid value for "minValue", expected "number"
[20240828-17:09:09:211] [ERROR] - envire_types::Invalid configuration for type envire::types::motors::PID; item name: rover_5connector_roll
```

This is the used configuration:
```
motors:
- d: 0
  i: 0
  joint: connector_roll
  maxEffort: 50.0
  maxSpeed: 0.349066
  maxValue: 0.523599
  minValue: -0.523599
  name: connector_roll
  p: 20.0
  type: PID
```

Maybe ConfigSchema.validate can't handle negative doubles?
